Add Create Flow screen
MLH-Fellowship/onboardio pull request #17
Opened 2020-09-25 19:34 UTC by utkarsh-dixit

![Create Flow Screen](https://i.imgur.com/DCkxcWB.png)

2020-09-25 19:41 UTC, flozender requested changes
LGTM, just see if you want to get rid of the .env

2020-09-25 19:41 UTC, flozender commented on server/.env
> +MONGODB=mongodb+srv://cheesetouched:68A2sS8P5XSv6Ur@hackathon.ea6nb.mongodb.net/onboardio?retryWrites=true&w=majority
Oops

2020-09-25 20:05 UTC, flozender commented
Also, does it work with dark mode as well? Asking since you used a third party multi select.

2020-09-25 20:19 UTC, utkarsh-dixit commented
@flozender I'm still working to fix the dark mode for react-select.

2020-09-26 03:07 UTC, Cheesetouched approved these changes
Wow. It's looking really good UI wise. 👍

2020-09-26 05:02 UTC, flozender commented
Let's merge when you're ready!

2020-09-26 06:34 UTC, flozender approved these changes

2020-09-26 06:47 UTC, anje123 approved these changes
This is looking good

2020-09-26 06:55 UTC, merged